Add services field into package manifest.yml
elastic/package-spec pull request #125
Opened 2021-02-03 02:49 UTC by kaiyan-sheng

## What does this PR do?

This PR is to add a new `services` field option into the package `manifest.yml` file. For example:
```
services:
  - name: aws_ec2
    title: AWS EC2
    release: beta
    description: AWS EC2 Integration
    icons:
      - src: /img/logo_aws_ec2.svg
        title: logo aws ec2
        size: 32x32
        type: image/svg+xml
    data_streams:
      - ec2_logs
      - ec2_metrics
```

## Why is it important?

With this new field, we can expose services under a package to users as separate integrations in Fleet Integrations list. For example, instead of only showing users we support AWS integration, we can also show AWS EC2, AWS SNS and etc.

## Checklist

- [ ] I have added test packages to [`code/go/internal/validator/test/packages`](https://github.com/elastic/package-spec/tree/master/code/go/internal/validator/test/packages) that prove my change is effective.
- [ ] I have added an entry in [`versions/N/changelog.yml`](https://github.com/elastic/package-spec/blob/master/versions/1/changelog.yml).

## Related issues

- Relates https://github.com/elastic/package-spec/issues/122

2021-02-03 02:53 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-spec%2FPR-125/detail/PR-125/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-spec%2FPR-125/detail/PR-125/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-spec%2FPR-125/detail/PR-125/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-spec%2FPR-125/detail/PR-125/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://package-spec_125.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats


* Build Cause: `Pull request #125 opened`



* * Start Time: 2021-02-03T02:50:17.093+0000


* Duration: 3 min 24 sec


* Commit: 4c5353efff9f1797fc66f5ff2c4e7e97b6b844eb




</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->







### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-spec%2FPR-125/detail/PR-125/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
  
##### `Test`
<ul>
<li>Took 0 min 4 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/package-spec/pipelines/PR-125/runs/1/steps/178/log/?start=0">here</a></li>
<li>Description: <code>make test</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2021-02-03T02:53:39.982Z]         	Error:      	Received unexpected error:
[2021-02-03T02:53:39.982Z]         	            	found 1 validation error:
[2021-02-03T02:53:39.982Z]         	            	   1. file "../../internal/validator/test/packages/deploy_docker/manifest.yml" is invalid: schema unmarshalling failed (path: file:///1/manifest.spec.yml): yaml: line 299: mapping values are not allowed in this context
[2021-02-03T02:53:39.982Z]         	Test:       	TestValidateFile/deploy_docker
[2021-02-03T02:53:39.982Z] === RUN   TestValidateFile/missing_data_stream
[2021-02-03T02:53:39.982Z]     validator_test.go:51: 
[2021-02-03T02:53:39.982Z]         	Error Trace:	validator_test.go:51
[2021-02-03T02:53:39.982Z]         	Error:      	Received unexpected error:
[2021-02-03T02:53:39.982Z]         	            	found 1 validation error:
[2021-02-03T02:53:39.982Z]         	            	   1. file "../../internal/validator/test/packages/missing_data_stream/manifest.yml" is invalid: schema unmarshalling failed (path: file:///1/manifest.spec.yml): yaml: line 299: mapping values are not allowed in this context
[2021-02-03T02:53:39.982Z]         	Test:       	TestValidateFile/missing_data_stream
[2021-02-03T02:53:39.982Z] === RUN   TestValidateFile/input_template
[2021-02-03T02:53:39.982Z]     validator_test.go:51: 
[2021-02-03T02:53:39.982Z]         	Error Trace:	validator_test.go:51
[2021-02-03T02:53:39.982Z]         	Error:      	Received unexpected error:
[2021-02-03T02:53:39.983Z]         	            	found 1 validation error:
[2021-02-03T02:53:39.983Z]         	            	   1. file "../../internal/validator/test/packages/input_template/manifest.yml" is invalid: schema unmarshalling failed (path: file:///1/manifest.spec.yml): yaml: line 299: mapping values are not allowed in this context
[2021-02-03T02:53:39.983Z]         	Test:       	TestValidateFile/input_template
[2021-02-03T02:53:39.983Z] === RUN   TestValidateFile/bad_deploy_variants
[2021-02-03T02:53:39.983Z]     validator_test.go:54: 
[2021-02-03T02:53:39.983Z]         	Error Trace:	validator_test.go:54
[2021-02-03T02:53:39.983Z]         	Error:      	"found 3 validation errors:
[2021-02-03T02:53:39.983Z]         	            	   1. file "../../internal/validator/test/packages/bad_deploy_variants/_dev/deploy/variants.yml" is invalid: field (root): default is required
[2021-02-03T02:53:39.983Z]         	            	   2. file "../../internal/validator/test/packages/bad_deploy_variants/_dev/deploy/variants.yml" is invalid: field variants: Invalid type. Expected: object, given: array
[2021-02-03T02:53:39.983Z]         	            	   3. file "../../internal/validator/test/packages/bad_deploy_variants/manifest.yml" is invalid: schema unmarshalling failed (path: file:///1/manifest.spec.yml): yaml: line 299: mapping values are not allowed in this context
[2021-02-03T02:53:39.983Z]         	            	" should have 2 item(s), but has 3
[2021-02-03T02:53:39.983Z]         	Test:       	TestValidateFile/bad_deploy_variants
[2021-02-03T02:53:39.983Z] === RUN   TestValidateFile/missing_pipeline_dashes
[2021-02-03T02:53:39.983Z]     validator_test.go:54: 
[2021-02-03T02:53:39.983Z]         	Error Trace:	validator_test.go:54
[2021-02-03T02:53:39.983Z]         	Error:      	"found 2 validation errors:
[2021-02-03T02:53:39.983Z]         	            	   1. file "../../internal/validator/test/packages/missing_pipeline_dashes/data_stream/foo/elasticsearch/ingest_pipeline/default.yml" is invalid: document dashes are required (start the document with '---')
[2021-02-03T02:53:39.983Z]         	            	   2. file "../../internal/validator/test/packages/missing_pipeline_dashes/manifest.yml" is invalid: schema unmarshalling failed (path: file:///1/manifest.spec.yml): yaml: line 299: mapping values are not allowed in this context
[2021-02-03T02:53:39.983Z]         	            	" should have 1 item(s), but has 2
[2021-02-03T02:53:39.983Z]         	Test:       	TestValidateFile/missing_pipeline_dashes
[2021-02-03T02:53:39.983Z] === RUN   TestValidateFile/missing_image_files
[2021-02-03T02:53:39.983Z]     validator_test.go:54: 
[2021-02-03T02:53:39.983Z]         	Error Trace:	validator_test.go:54
[2021-02-03T02:53:39.983Z]         	Error:      	"found 1 validation error:
[2021-02-03T02:53:39.983Z]         	            	   1. file "../../internal/validator/test/packages/missing_image_files/manifest.yml" is invalid: schema unmarshalling failed (path: file:///1/manifest.spec.yml): yaml: line 299: mapping values are not allowed in this context
[2021-02-03T02:53:39.983Z]         	            	" should have 2 item(s), but has 1
[2021-02-03T02:53:39.983Z]         	Test:       	TestValidateFile/missing_image_files
[2021-02-03T02:53:39.983Z] --- FAIL: TestValidateFile (0.05s)
[2021-02-03T02:53:39.983Z]     --- FAIL: TestValidateFile/good (0.02s)
[2021-02-03T02:53:39.983Z]     --- FAIL: TestValidateFile/deploy_docker (0.00s)
[2021-02-03T02:53:39.983Z]     --- FAIL: TestValidateFile/missing_data_stream (0.00s)
[2021-02-03T02:53:39.983Z]     --- FAIL: TestValidateFile/input_template (0.01s)
[2021-02-03T02:53:39.983Z]     --- FAIL: TestValidateFile/bad_deploy_variants (0.00s)
[2021-02-03T02:53:39.983Z]     --- FAIL: TestValidateFile/missing_pipeline_dashes (0.01s)
[2021-02-03T02:53:39.983Z]     --- FAIL: TestValidateFile/missing_image_files (0.01s)
[2021-02-03T02:53:39.983Z] === RUN   TestValidateItemNotAllowed
[2021-02-03T02:53:39.983Z] === RUN   TestValidateItemNotAllowed/wrong_kibana_filename
[2021-02-03T02:53:39.983Z]     validator_test.go:140: 
[2021-02-03T02:53:39.983Z]         	Error Trace:	validator_test.go:140
[2021-02-03T02:53:39.983Z]         	            				validator_test.go:98
[2021-02-03T02:53:39.983Z]         	Error:      	"found 11 validation errors:
[2021-02-03T02:53:39.983Z]         	            	   1. item [b7e55b73-97cc-44fd-8555-d01b7e13e70d.json]  [...]

2021-02-03 06:54 UTC, ruflin requested changes
Can we please hold off on PR's until we agree on the right format to use in https://github.com/elastic/package-spec/issues/122 ?

2021-02-03 13:48 UTC, ycombinator commented
@ruflin Sure, but I thought there was agreement in #122. Can you point to something in #122 where there is disagreement? Maybe I missed something...

2021-02-19 19:18 UTC, kaiyan-sheng commented
Closing this draft after we discussed more on the design.

2021-02-19 19:18 UTC, closed without merging