update csp rule template benchmark field
elastic/package-spec pull request #365
Opened 2022-06-29 06:51 UTC by CohenIdo

Update `benchmark` field in  `csp-rule-template` asset

2022-06-29 07:04 UTC, elasticmachine commented
## :green_heart: Build Succeeded


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-spec%2FPR-365/detail/PR-365/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-spec%2FPR-365/detail/PR-365/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-spec%2FPR-365/detail/PR-365/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-spec%2FPR-365/detail/PR-365/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://package-spec_365.docs-preview.app.elstc.co/diff)  [![preview](https://img.shields.io/badge/elastic-observability-blue)](https://ci-stats.elastic.co/app/apm/services/beats-ci/transactions/view?rangeFrom=2022-06-29T06:42:19.522Z&rangeTo=2022-06-29T07:02:19.522Z&transactionName=Ingest-manager/package-spec/PR-{number}&transactionType=job&latencyAggregationType=avg&traceId=d9909aff2c69ac9fe8ad02afaa603b1c&transactionId=b06ece321b705683)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats




* Start Time: 2022-06-29T06:52:19.522+0000


* Duration: 12 min 40 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY -->














## :robot: GitHub comments

To re-run your PR in the CI, just comment with:



- `/test` : Re-trigger the build.




<!--COMMENT_GENERATED_WITH_ID_comment.id-->

2022-06-29 07:46 UTC, mtojek approved these changes
It looks like a breaking change in format, but as long as we don't have advanced validation on the `csp_rule_template` format, it shouldn't be breaking any existing package.

2022-06-29 09:31 UTC, jsoriano commented on versions/1/changelog.yml
> +    link: https://github.com/elastic/package-spec/pull/365
This PR is only changing a sample test package, there is no user-facing change. Do we need a changelog entry for that?
```suggestion
```

2022-06-29 09:31 UTC, jsoriano commented on test/packages/good/kibana/csp_rule_template/good-csp-rule-template-abc-1.json
> +    "benchmark": [{ "name": "CIS Kubernetes V1.23", "id": "cis_k8s", "version": "v1.0.0" }],
What is the context of this change? Is this template invalid? Should we add some validation to the spec?

2022-07-05 09:15 UTC, kfirpeled requested changes
halting the change, we've decided not to go with this approach. 
The original idea was to share metadata of rules between benchmarks but as we recently learned they don't match. Besides that, these rule templates are going to be imported and generated directly from CIS. 
Therefore, it is better not to share metadata between rules.

2022-07-05 09:15 UTC, closed without merging